#!/bin/bash
autorandr -c &
sxhkd -m 1 &
~/.config/bspwm/screen.sh &
~/.config/polybar/launch.sh &
fcitx5 -d &
picom -b --config ~/.config/picom/picom.conf &
xautolock -time 5 -locker '~/scripts/lockscreen.sh' -corners 0-00 -killtime 20 -killer '/usr/bin/systemctl suspend' -detectsleep -secure &
amixer set Master mute &
# xautolock -time 5 -locker '~/scripts/lockscreen.sh' -corners 0-00 -secure &
xss-lock --transfer-sleep-lock -- betterlockscreen -l &
xsetroot -cursor_name left_ptr &
nm-applet &
ectool raw 0x3E0C d1,d1,b3,b1,w11 &
ectool raw 0x3E0C d1,d1,b1,b3,wE01F &
betterlockscreen -u ~/Pictures/Wallpaper/framework_wallpaper.png &
feh --bg-fill ~/Pictures/Wallpaper/WP_Laser_Up-2560x1440_00229.jpg &
~/application/pcloud &

bspc config window_gap 2
bspc config normal_border_color "#3B4252"
bspc config active_border_color "#81A1C1"
bspc config focused_border_color "#88C0D0"
bspc config presel-feedback color "#88C0D0"
bspc config top_padding 40
bspc config bottom_padding 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus follows pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp deskt='^7' state=floating follow=on
bspc rule -a firefox desktop='^4' follow=on
bspc rule -a Spotify desktop='^10' follow=on
bspc rule -a discord desktop='^9' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Com.cisco.anyconnect.gui desktop='^10' follow=on
bspc rule -a obsidian desktop='^1' follow on

# scratchpad
bspc rule -a scpad sticky=on state=floating rectangle=1800x1200+250+250
