#!/bin/sh
# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
#alias nvimrc='nvim ~/.config/nvim/'

# Exa 
alias l='exa'
alias la='exa -a'
alias ll='exa -lah'
alias ls='exa --color=auto'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Confirm before overwriting something
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# program shortcuts
alias v='nvim'
alias m='micro'
alias wifi='nmtui'
alias zotero='cd ~/application/zotero/ && devour bash zotero'
alias wally='cd ~/application && ./wally'
alias wake='cd ~/scripts && ./wake.sh'
# open pdf
alias fw='devour evince ~/Documents/school/university/osu/senior/fall/fw315/Gene\ Helfman,\ Bruce\ B.\ Collette,\ Douglas\ E.\ Facey,\ Brian\ W.\ Bowen\ -\ The\ Diversity\ of\ Fishes_\ Biology,\ Evolution,\ and\ Ecology\ \(2009,\ Wiley-Blackwell\)\ -\ libgen.lc.pdf'
alias geog='devour evince ~/Documents/school/university/osu/senior/fall/geog360/Paul\ Bolstad\ -\ GIS\ Fundamentals_\ a\ First\ Text\ on\ Geographic\ Information\ Systems\ \(2019,\ Eider\ Press\)\ -\ libgen.li.pdf'
